// THIS FILE IS AUTOMATICALLY GENERATED. DO NOT MODIFY IT.

import { Document } from '@contentful/rich-text-types';
import { Asset, Entry } from 'contentful';

export type IHomepageFields = {
  /** Title */
  title: string;

  /** Meta */
  meta: IMeta;

  /** Hero Keywords */
  heroKeywords: string[];

  /** About */
  about: Document;

  /** Author Image */
  authorImage: Asset;

  /** Project List */
  projectList: IProject[];
};

export interface IHomepage extends Entry<IHomepageFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: 'homepage';
        linkType: 'ContentType';
        type: 'Link';
      };
    };
  };
}

export interface ILanguageFields {
  /** Title */
  title: string;

  /** Lang */
  lang: string;

  /** About */
  about: string;

  /** Projects */
  projects: string;

  /** Contact */
  contact: string;

  /** Contact Description */
  contactDescription: string;

  /** Title First */
  titleFirst: string;

  /** Title Second */
  titleSecond: string;

  /** Copyright */
  copyright: string;

  /** Form Success */
  formSuccess: string;

  /** Form Error */
  formError: string;

  /** Form Try Again */
  formTryAgain: string;

  /** Recaptcha Error */
  recaptchaError: string;

  /** Name Placeholder */
  namePlaceholder: string;

  /** Name Required */
  nameRequired: string;

  /** Email Placeholder */
  emailPlaceholder: string;

  /** Email Required */
  emailRequired: string;

  /** Email Not Valid */
  emailNotValid: string;

  /** Message Placeholder */
  messagePlaceholder: string;

  /** Message Required */
  messageRequired: string;

  /** Form Submit */
  formSubmit: string;
}

export interface ILanguage extends Entry<ILanguageFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: 'language';
        linkType: 'ContentType';
        type: 'Link';
      };
    };
  };
}

export interface IMetaFields {
  /** Title */
  title: string;

  /** Description */
  description: string;

  /** Image */
  image: Asset;

  /** Author */
  author: string;
}

export interface IMeta extends Entry<IMetaFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: 'meta';
        linkType: 'ContentType';
        type: 'Link';
      };
    };
  };
}

export interface IProjectFields {
  /** Title */
  title: string;

  /** Description */
  description: string;

  /** Techs */
  techs: string[];

  /** Image */
  image: Asset;

  /** Link */
  link: string;
}

export interface IProject extends Entry<IProjectFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: 'project';
        linkType: 'ContentType';
        type: 'Link';
      };
    };
  };
}

export interface ISettingsFields {
  /** Title */
  title: string;

  /** Logo Light */
  logoLight: Asset;

  /** Logo Dark */
  logoDark: Asset;

  /** Navigation */
  navigation: string[];

  /** Resume */
  resume: Asset;

  /** Socials */
  socials: ISocials;

  /** Email */
  email: string;
}

export interface ISettings extends Entry<ISettingsFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: 'settings';
        linkType: 'ContentType';
        type: 'Link';
      };
    };
  };
}

export interface ISocialsFields {
  /** Github */
  github?: string | undefined;

  /** Linkedin */
  linkedin?: string | undefined;

  /** Instagram */
  instagram?: string | undefined;

  /** Facebook */
  facebook?: string | undefined;
}

export interface ISocials extends Entry<ISocialsFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: 'socials';
        linkType: 'ContentType';
        type: 'Link';
      };
    };
  };
}

export type ContentType = 'homepage' | 'language' | 'meta' | 'project' | 'settings' | 'socials';

export type LocaleCode = string | undefined;

export type ContentfulDefaultLocaleCode = 'en';
