// THIS FILE IS AUTOMATICALLY GENERATED. DO NOT MODIFY IT.

import { BLOCKS } from '@contentful/rich-text-types';

export type IImage = {
  url: string;
  title: string;
  width: number;
  height: number;
};

export type IAssets = {
  sys: {
    id: string;
  };
  url: string;
  title: string;
  width: number;
  height: number;
};

export type IRichText = {
  json: {
    nodeType: BLOCKS.DOCUMENT;
    content: any[];
    data: any;
  };
};

export type IHomepageFields = {
  /** Title */
  title: string;

  /** Meta */
  meta: IMetaFields;

  /** Hero Keywords */
  heroKeywords: string[];

  /** About */
  about: IRichText;

  /** About */
  deneme: IRichText;

  /** Author Image */
  authorImage: IImage;

  /** Project List */
  projectListCollection: {
    items: IProjectFields[];
  };
};

export type ICustom404Fields = {
  /** Title */
  title: string;

  /** Meta */
  meta: IMetaFields;

  /** Button */
  button: string;
};

export type ILanguageFields = {
  /** Title */
  title: string;

  /** Lang */
  lang: string;

  /** About */
  about: string;

  /** Projects */
  projects: string;

  /** Contact */
  contact: string;

  /** Contact Description */
  contactDescription: string;

  /** Title First */
  titleFirst: string;

  /** Title Second */
  titleSecond: string;

  /** Copyright */
  copyright: string;

  /** Form Success */
  formSuccess: string;

  /** Form Error */
  formError: string;

  /** Form Try Again */
  formTryAgain: string;

  /** Recaptcha Error */
  recaptchaError: string;

  /** Name Placeholder */
  namePlaceholder: string;

  /** Name Required */
  nameRequired: string;

  /** Email Placeholder */
  emailPlaceholder: string;

  /** Email Required */
  emailRequired: string;

  /** Email Not Valid */
  emailNotValid: string;

  /** Message Placeholder */
  messagePlaceholder: string;

  /** Message Required */
  messageRequired: string;

  /** Form Submit */
  formSubmit: string;
};

export type IMetaFields = {
  /** Title */
  title: string;

  /** Description */
  description?: string;

  /** Image */
  image: IImage;

  /** Author */
  author?: string;
};

export type IProjectFields = {
  /** Title */
  title: string;

  /** Description */
  description: string;

  /** Techs */
  techs: string[];

  /** Image */
  image: IImage;

  /** Link */
  link: string;
};

export type ISettingsFields = {
  /** Title */
  title: string;

  /** Logo Light */
  logoLight: IImage;

  /** Logo Dark */
  logoDark: IImage;

  /** Navigation */
  navigation: string[];

  /** Resume */
  resume: IImage;

  /** Socials */
  socials: ISocialsFields;

  /** Email */
  email: string;

  /** Meta */
  meta: IMetaFields;

  /** Author */
  author: string;
};

export type ISocialsFields = {
  /** Github */
  github?: string | undefined;

  /** Linkedin */
  linkedin?: string | undefined;

  /** Instagram */
  instagram?: string | undefined;

  /** Facebook */
  facebook?: string | undefined;
};

export type ContentType = 'homepage' | 'language' | 'meta' | 'project' | 'settings' | 'socials';

export type LocaleCode = string | undefined;

export type ContentfulDefaultLocaleCode = 'en';
